// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz-tjXnwhKBjWtewkOAR44Pmt3-3bMGSY',
    appId: '1:242559025057:web:4c6387e213fa41b32855e0',
    messagingSenderId: '242559025057',
    projectId: 'fir-auth-42f09',
    authDomain: 'fir-auth-42f09.firebaseapp.com',
    storageBucket: 'fir-auth-42f09.firebasestorage.app',
    measurementId: 'G-PJSL0M0MJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBMEqs214jrWta5LAXe9v5csNiEu98-FU',
    appId: '1:242559025057:android:3527628e5009fa2e2855e0',
    messagingSenderId: '242559025057',
    projectId: 'fir-auth-42f09',
    storageBucket: 'fir-auth-42f09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5WmcnQBqyBEHNi5DUnIiwqE7q9JJI7DI',
    appId: '1:242559025057:ios:0c836151939688752855e0',
    messagingSenderId: '242559025057',
    projectId: 'fir-auth-42f09',
    storageBucket: 'fir-auth-42f09.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5WmcnQBqyBEHNi5DUnIiwqE7q9JJI7DI',
    appId: '1:242559025057:ios:0c836151939688752855e0',
    messagingSenderId: '242559025057',
    projectId: 'fir-auth-42f09',
    storageBucket: 'fir-auth-42f09.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz-tjXnwhKBjWtewkOAR44Pmt3-3bMGSY',
    appId: '1:242559025057:web:de29f4e295194c882855e0',
    messagingSenderId: '242559025057',
    projectId: 'fir-auth-42f09',
    authDomain: 'fir-auth-42f09.firebaseapp.com',
    storageBucket: 'fir-auth-42f09.firebasestorage.app',
    measurementId: 'G-53Z50HCXXF',
  );
}
